FROM openjdk:17
LABEL maintainer="edwardwong503@gmail.com"
ADD target/fianlproject-0.0.1-SNAPSHOT.jar fianlproject-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","fianlproject-0.0.1-SNAPSHOT.jar"]
EXPOSE 8090