server:
  port : 8091

api: 
  finnhublaceholder:
    domain: "finnhub.io/api/v1"
    endpoints: 
      users: "/users"
      posts: "/posts"
      comments: "/comments"

#//'spring.data.redis.host' 

spring:
  data: 
    redis:
     host: "localhost"
  redis:
    data:
      port: 6379