
spring:
  datasource:
    #driverClassName: "org.hibernate.dialect.PostgreSQLDialect"
    driverClassName: org.postgresql.Driver
    #url: "jdbc:postgresql://localhost:5432/${database.postgres}"
    url: jdbc:postgresql://localhost:5432/finaical_data
    username: postgres
    password: admin1234

  jpa:
    #properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDiale
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update # update
server:
  port: 8088

currency: 
  type: usd

url: 
  domain: http://edwinsung.com/crypto/coingecko/api/v1/coins
  #domain: http://localhost:8090/crypto/coingecko/api/v1/coins
  #stockQuote: http://localhost:8091/stock/finnhub/api/v1/quote?symbol=
  stockQuote: http://ec2-184-72-201-165.compute-1.amazonaws.com:8091/stock/finnhub/api/v1/quote?symbol=
  #stockProfile: http://localhost:8091/stock/finnhub/api/v1/profile2?symbol=
  stockProfile: http://ec2-184-72-201-165.compute-1.amazonaws.com:8091/stock/finnhub/api/v1/profile2?symbol=

housekeeping:
  time: 24
